name: Codex Accessibility Overlays
on:
  push:
    branches: [ "main" ]
    paths:
      - 'public/**'
      - 'audio/**'
      - 'scripts/**'
      - '.github/workflows/accessibility.yml'
  schedule:
    - cron: '0 4 * * 1'   # weekly guard run
  workflow_dispatch:
permissions:
  contents: write
jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build overlays
        env:
          VOICE_LANGS: ${{ vars.VOICE_LANGS }}
        run: |
          set -euo pipefail
          bash scripts/codex_accessibility.sh
      - name: Commit overlays (if changed)
        run: |
          set -e
          if ! git diff --quiet; then
            git config user.name  "codex-bot"
            git config user.email "codex-bot@users.noreply.github.com"
            git add -A
            git commit -m "Accessibility: overlays & captions manifest"
            git push
          fi
