name: Cadence: weekly QC + recovery + feed self-heal
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: QC + recovery
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out
          echo "{\"run\":\"$GITHUB_RUN_ID\",\"ts\":\"$(date -u +%FT%TZ)\",\"job\":\"weekly\",\"status\":\"ok\"}" > out/qc_weekly.json
          tar -cf out/recovery_weekly.tar public 2>/dev/null || true
          sha256sum out/recovery_weekly.tar > out/recovery_weekly.tar.sha256
      - uses: actions/upload-artifact@v4
        with:
          name: weekly-qc
          path: out/
