name: Cadence: quarterly QC + recovery + feed self-heal
on:
  schedule:
    - cron: '0 3 1 */3 *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  quarterly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: QC + recovery
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out
          echo "{\"run\":\"$GITHUB_RUN_ID\",\"ts\":\"$(date -u +%FT%TZ)\",\"job\":\"quarterly\",\"status\":\"ok\"}" > out/qc_quarterly.json
          tar -cf out/recovery_quarterly.tar public 2>/dev/null || true
          sha256sum out/recovery_quarterly.tar > out/recovery_quarterly.tar.sha256
      - uses: actions/upload-artifact@v4
        with:
          name: quarterly-qc
          path: out/
