name: Cadence: quarterly QC + recovery + feed self-heal
on: { schedule: [ { cron: '0 3 1 */3 *' } ], workflow_dispatch: {} }
permissions: { contents: read }
jobs:
  quarterly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: QC / recovery / feed self-heal
        run: echo "[quarterly] QC task placeholder"
