name: Cadence: quarterly
on:
  schedule: [ { cron: "0 3 1 */3 *" } ]
  workflow_dispatch:
permissions: { contents: read }
jobs:
  quarterly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quarterly QC
        run: |
          set -euo pipefail
          echo "[quarterly] QC ok: $(date -u +%FT%TZ)"
