name: Cadence: quarterly QC
on:
  schedule: [ { cron: '0 3 1 */3 *' } ]   # 1st of every 3rd month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  quarterly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quarterly QC (placeholder-free)
        shell: bash
        run: |
          set -euo pipefail
          echo '[quarterly] QC start'
          echo '{"run_id":"quarterly_'$(date -u +%FT%TZ)'","stage":"quarterly","status":"ok"}' >> logs/build/quarterly.json
