name: Cadence: quarterly QC + recovery
on:
  schedule:
    - cron: '0 3 1 */3 *'   # 1st of every 3rd month, 03:00 UTC
  workflow_dispatch:
permissions: { contents: read }
jobs:
  quarterly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quarterly QC (placeholder)
        shell: bash
        run: |
          set -euo pipefail
          echo "[quarterly] QC ok"
