name: Cadence: quarterly QC + recovery

on:
  schedule:
    - cron: "0 3 1 */3 *"    # 1st day of every quarter 03:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quarterly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quarterly QC
        run: |
          set -eu
          echo "[quarterly] QC task placeholder"
