name: Cadence — Quarterly Arc Milestone
on: { schedule: [ { cron: '10 10 1 1,4,7,10 *' } ], workflow_dispatch: {} }
jobs: { run: { runs-on: ubuntu-latest, steps: [ { uses: actions/checkout@v4 }, { run: sudo apt-get update -y && sudo apt-get install -y jq }, { run: CADENCE_MODE=quarterly REPO_SLUG="${{ github.repository }}" FEED_URL="${{ vars.FEED_URL }}" bash scripts/cadence.sh } ] } }
