name: Cadence: quarterly QC + recovery
on:
  schedule: [ { cron: '0 3 1 */3 *' } ]   # 1st of every 3rd month
  workflow_dispatch:
permissions: { contents: read }
jobs:
  quarterly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quarterly QC (placeholder)
        run: |
          set -euo pipefail
          echo "[quarterly] QC task"
