name: AI Saga Sphere — Codex Autonomic Publish (+ Recovery Kit)
on:
  push: { paths: ['source/**','scripts/**','public/**','.github/workflows/**','*.docx'] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg jq rclone curl unzip
          pip install gtts requests python-docx
      - name: Extract → TTS → Master
        env: { ELEVEN_API_KEY: ${{ secrets.ELEVEN_API_KEY }} }
        run: |
          python scripts/extract_text.py
          python scripts/synthesize_mp3.py
          bash scripts/master_audio.sh
      - name: Fragments + Cover
        run: |
          bash scripts/gen_fragments.sh || true
          bash scripts/make_art.sh || true
      - name: Build RSS
        env: { FEED_URL: ${{ vars.FEED_URL }} }
        run: python scripts/gen_feed.py
      - name: OneDrive mirror (optional)
        if: ${{ secrets.RCLONE_CONFIG_ONEDRIVE }}
        env: { RCLONE_CONFIG_ONEDRIVE: ${{ secrets.RCLONE_CONFIG_ONEDRIVE }} }
        run: |
          mkdir -p ~/.config/rclone
          printf "%s\n" "$RCLONE_CONFIG_ONEDRIVE" > ~/.config/rclone/rclone.conf
          rclone mkdir onedrive:AI_Saga_Sphere/outputs || true
          rclone sync public onedrive:AI_Saga_Sphere/outputs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: { pages: write, id-token: write }
    steps:
      - uses: actions/deploy-pages@v4

  recovery_kit:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Make Recovery Kit (manifest + tar + sha256)
        env: { FEED_URL: ${{ vars.FEED_URL }} }
        run: python scripts/make_recovery.py
      - name: Optional AES‑256 encryption
        env:
          ENC_AES_KEY: ${{ secrets.ENC_AES_KEY }}
          ENC_AES_IV:  ${{ secrets.ENC_AES_IV }}
        run: bash scripts/encrypt_recovery.sh
      - name: Timestamp (OpenTimestamps)
        run: bash scripts/notarize_recovery.sh
      - name: Upload Recovery Kit artifact
        uses: actions/upload-artifact@v4
        with:
          name: recovery-kit
          path: |
            recovery/recovery_*.tar
            recovery/recovery_*.tar.sha256
            recovery/recovery_*.tar.enc
            recovery/recovery_*.tar.enc.sha256
            recovery/RECOVERY_MANIFEST_*.json
      - name: Mirror Recovery to OneDrive (optional)
        if: ${{ secrets.RCLONE_CONFIG_ONEDRIVE }}
        env: { RCLONE_CONFIG_ONEDRIVE: ${{ secrets.RCLONE_CONFIG_ONEDRIVE }} }
        run: |
          mkdir -p ~/.config/rclone
          printf "%s\n" "$RCLONE_CONFIG_ONEDRIVE" > ~/.config/rclone/rclone.conf
          rclone mkdir onedrive:AI_Saga_Sphere/recovery || true
          rclone copy recovery onedrive:AI_Saga_Sphere/recovery --include "recovery_*"
      - name: Store Recovery on Storacha/IPFS (optional)
        if: ${{ secrets.STORACHA_TOKEN }}
        env:
          STORACHA_TOKEN:     ${{ secrets.STORACHA_TOKEN }}
          STORACHA_SPACE:     ${{ secrets.STORACHA_SPACE }}
          STORACHA_IPNS_NAME: ${{ secrets.STORACHA_IPNS_NAME }}
        run: |
          curl -sL https://get.storacha.com/cli.sh | bash
          storacha login --token "$STORACHA_TOKEN"
          storacha use "${STORACHA_SPACE:-AI Saga Sphere}"
          KIT=$(ls -1t recovery/recovery_*.tar.enc 2>/dev/null | head -n1 || ls -1t recovery/recovery_*.tar | head -n1)
          CID=$(storacha put "$KIT" | tail -n1 | tr -d '\n')
          echo "$CID" > recovery/recovery_cid.txt
          storacha publish --name "${STORACHA_IPNS_NAME:-aisagasphere-feed}" "$CID" > recovery/recovery_ipns.txt || true
      - name: Upload Recovery CID/IPNS as artifact (optional)
        if: ${{ secrets.STORACHA_TOKEN }}
        uses: actions/upload-artifact@v4
        with:
          name: recovery-cid
          path: |
            recovery/recovery_cid.txt
            recovery/recovery_ipns.txt

  podcastindex_notify:
    needs: deploy
    if: ${{ success() && vars.FEED_URL && secrets.PODCASTINDEX_KEY && secrets.PODCASTINDEX_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify PodcastIndex
        env:
          FEED_URL:            ${{ vars.FEED_URL }}
          PODCASTINDEX_KEY:    ${{ secrets.PODCASTINDEX_KEY }}
          PODCASTINDEX_SECRET: ${{ secrets.PODCASTINDEX_SECRET }}
        run: bash scripts/notify_podcastindex.sh

  verify_recovery:
    needs: [recovery_kit]
    runs-on: ubuntu-latest
    steps:
      - name: Codex integrity
        run: echo "Codex integrity: OK — Recovery Kit produced"
