name: Codex Log v2 Schema Check
on:
  schedule: [ { cron: "25 3 * * *" } ]
  push:
    branches: [ "main" ]
    paths:
      - "logs/codex/**"
      - "schemas/codex_log.schema.json"
      - ".github/workflows/codex_log_schema.yml"
  workflow_dispatch:
permissions: { contents: read }
concurrency: { group: "codex-log-schema", cancel-in-progress: true }
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tooling
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq python3-pip
          pip3 install --user jsonschema
      - name: Validate Codex JSONL events
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(logs/codex/*.jsonl)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No codex logs yet; exiting 0"
            exit 0
          fi
          for f in "${files[@]}"; do
            while IFS= read -r line || [ -n "$line" ]; do
              python3 - <<'PY'
import sys,json
from jsonschema import validate,exceptions
schema=json.load(open("schemas/codex_log.schema.json"))
line=sys.stdin.read()
try:
  obj=json.loads(line)
  validate(obj,schema)
except Exception as e:
  print("Schema error:",e); sys.exit(1)
PY
            done < "$f"
          done
