name: Codex Kits Index (site publish)

on:
  push:
    branches: [ "main" ]
    paths:
      - "recovery_kits/**"
      - "scripts/build_kits_index.sh"
      - ".github/workflows/codex_kits_index.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y jq
      - name: Build Kits index
        run: |
          set -euo pipefail
          chmod +x scripts/build_kits_index.sh
          ./scripts/build_kits_index.sh
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build-index
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
