name: Codex Publish
on:
  push:
    branches: [ "main" ]
    paths:
      - "scripts/**"
      - "public/**"
      - ".github/workflows/codex_publish.yml"
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build codex artifacts
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p public
          echo '<!-- codex build '$(date -u +%FT%TZ)' -->' >> public/index.html
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
