name: Codex Recovery Kit (daily)
on:
  schedule: [ { cron: "10 3 * * *" } ]
  workflow_dispatch:
permissions: { contents: read }
concurrency: { group: codex-recovery, cancel-in-progress: true }
jobs:
  kit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -y && sudo apt-get install -y ffmpeg sox jq
      - run: chmod +x bin/codex_recovery.sh || true
      - name: Build (use latest audio if present)
        run: |
          set -euo pipefail
          if ls public/audio/*.mp3 >/dev/null 2>&1; then
            latest="$(ls -1t public/audio/*.mp3 | head -n1)"
            bin/codex_recovery.sh "$latest"
          else
            echo "no audio available; skipping"; exit 0
          fi
          echo "KIT_DIR=$(ls -1dt recovery_kits/* | head -n1)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with: { name: codex-recovery-${{ env.KIT_DIR }}, path: ${{ env.KIT_DIR }}, retention-days: 30 }
