name: Codex Publish (build + Pages deploy)
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'scripts/**'
      - 'public/**'
      - '.github/workflows/**'
permissions:
  contents: write
  pages: write
  id-token: write
concurrency: { group: pages, cancel-in-progress: true }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build site
        run: |
          set -euo pipefail
          mkdir -p public
          test -s public/index.html || echo "<!doctype html><meta charset=utf-8><title>AI Saga Sphere</title><h1>AI Saga Sphere</h1>" > public/index.html
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }
  deploy:
    needs: build
    permissions: { pages: write, id-token: write }
    environment: { name: github-pages, url: ${{ steps.deployment.outputs.page_url }} }
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
