name: Codex Recovery
on:
  workflow_dispatch:
permissions: { contents: write }
jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make recovery kit
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p recovery
          tar -cf recovery/site_${{ github.run_id }}.tar public 2>/dev/null || true
          sha256sum recovery/site_${{ github.run_id }}.tar > recovery/site_${{ github.run_id }}.sha256 || true
      - name: Commit recovery kit
        run: |
          git config user.name "codex-bot"
          git config user.email "actions@users.noreply.github.com"
          git add recovery || true
          git commit -m "Recovery kit ${{ github.run_id }}" || true
          git pull --rebase --autostash origin main || true
          git push origin HEAD:main || true
