name: Codex Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure minimal feed.xml exists
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f feed.xml ]; then
            cat > feed.xml <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>AI Saga Sphere Pipeline</title>
  <updated>2000-01-01T00:00:00Z</updated>
  <id>tag:bootstrap</id>
  <entry>
    <title>Codex Bootstrap</title>
    <updated>2000-01-01T00:00:00Z</updated>
    <id>tag:codex-bootstrap</id>
  </entry>
</feed>
XML
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
