name: AI Saga Sphere — Codex Autonomic Publish (Visuals + Benchmarks + i18n)
on:
  push: { paths: ['source/**','scripts/**','voices.json','assets/**','public/**','.github/workflows/**'] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg jq rclone curl unzip
          pip install gtts requests python-docx pillow
      - name: Extract manuscript
        run: python scripts/extract_text.py
      - name: Synthesize (multi‑voice if present else single)
        env: { ELEVEN_API_KEY: ${{ secrets.ELEVEN_API_KEY }} }
        run: |
          if [ -f voices.json ] && [ -f scripts/speak_multi.py ]; then
            python scripts/speak_multi.py
            bash scripts/mix_and_master.sh
          else
            python scripts/synthesize_mp3.py
            bash scripts/master_audio.sh
          fi
      - name: Build RSS
        env: { FEED_URL: ${{ vars.FEED_URL }} }
        run: python scripts/gen_feed.py
      - name: Quadrant Grid
        run: python scripts/make_quadrant_grid.py
      - name: Audio Benchmarks
        run: |
          pip install --quiet "argostranslate==1.9.0" || true
          python scripts/bench_audio.py
      - name: i18n — install translators (optional)
        if: ${{ vars.LANG_CODES }}
        env: { LANG_CODES: ${{ vars.LANG_CODES }} }
        run: bash scripts/translate_install.sh
      - name: i18n — translate text (optional)
        if: ${{ vars.LANG_CODES }}
        env: { LANG_CODES: ${{ vars.LANG_CODES }} }
        run: python scripts/translate_text.py
      - name: i18n — dubs (optional)
        if: ${{ vars.LANG_CODES }}
        env: { LANG_CODES: ${{ vars.LANG_CODES }} }
        run: python scripts/dub_multilang.py
      - name: i18n — captions (optional)
        if: ${{ vars.LANG_CODES }}
        env: { LANG_CODES: ${{ vars.LANG_CODES }} }
        run: |
          if [ -f public/captions/book0_story_premise.srt ]; then
            python scripts/translate_captions.py
          fi
      - name: OneDrive mirror (optional)
        if: ${{ secrets.RCLONE_CONFIG_ONEDRIVE }}
        env: { RCLONE_CONFIG_ONEDRIVE: ${{ secrets.RCLONE_CONFIG_ONEDRIVE }} }
        run: |
          mkdir -p ~/.config/rclone
          printf "%s\n" "$RCLONE_CONFIG_ONEDRIVE" > ~/.config/rclone/rclone.conf
          rclone mkdir onedrive:AI_Saga_Sphere/outputs || true
          rclone sync public onedrive:AI_Saga_Sphere/outputs
      - name: Storacha publish + IPNS (optional)
        if: ${{ secrets.STORACHA_TOKEN }}
        env:
          STORACHA_TOKEN:     ${{ secrets.STORACHA_TOKEN }}
          STORACHA_SPACE:     ${{ secrets.STORACHA_SPACE }}
          STORACHA_IPNS_NAME: ${{ secrets.STORACHA_IPNS_NAME }}
        run: |
          curl -sL https://get.storacha.com/cli.sh | bash
          storacha login --token "$STORACHA_TOKEN"
          storacha use "${STORACHA_SPACE:-AI Saga Sphere}"
          CID=$(storacha put public | tail -n1 | tr -d '\n'); echo "$CID" > public/ipfs.txt
          storacha publish --name "${STORACHA_IPNS_NAME:-aisagasphere-feed}" "$CID" > public/ipns.txt || true
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: { pages: write, id-token: write }
    steps:
      - uses: actions/deploy-pages@v4

  podcastindex_notify:
    needs: deploy
    if: ${{ success() && vars.FEED_URL && secrets.PODCASTINDEX_KEY && secrets.PODCASTINDEX_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify PodcastIndex
        env:
          FEED_URL:            ${{ vars.FEED_URL }}
          PODCASTINDEX_KEY:    ${{ secrets.PODCASTINDEX_KEY }}
          PODCASTINDEX_SECRET: ${{ secrets.PODCASTINDEX_SECRET }}
        run: bash scripts/notify_podcastindex.sh

  verify_recovery:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Codex integrity
        run: echo "Codex integrity: OK"
