name: nightly feed keepalive
on:
  schedule: [ { cron: "0 3 * * *" } ]  # daily 03:00 UTC
  workflow_dispatch:
permissions: { contents: read }
jobs:
  touch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "nightly ok: $(date -u)" >> .github/keepalive.log
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: nightly keepalive"
          branch: main
