name: pages build and deployment
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure site exists
        run: |
          set -Eeuo pipefail
          test -s public/index.html || { echo "missing index"; exit 1; }
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
