name: Codex Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Ensure a nojekyll + minimal index so Pages will build
      - name: Bootstrap public files
        run: |
          mkdir -p public
          [ -f public/.nojekyll ] || echo > public/.nojekyll
          [ -f public/index.html ] || cat > public/index.html <<'HTML'
          <!doctype html><meta charset="utf-8"><title>AI Saga Sphere</title>
          <h1>AI Saga Sphere</h1><p>Codex feed: <a href="feed.xml">feed.xml</a></p>
          HTML
          # Preserve feed.xml if repo already has one
          [ -f feed.xml ] && cp feed.xml public/feed.xml || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
