name: Codex Pages Scaffold
on:
  push: { branches: [ main ] }
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -eu
          mkdir -p public
          echo "<html><head><title>AI Saga Sphere</title></head><body><h1>Codex Pages Scaffold</h1></body></html>" > public/index.html
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
